### ISSUE TITLE
Editor Extensions Version: 2.19.170403 not working in Unity 5.6f3

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/UnityEditorExtensions#64]
**error x3:** 
Assets/PlayFabEditorExtensions/Editor/Scripts/Components/MenuComponent.cs(20,53): error CS0103: The name `PlayFabEditorHelper' does not exist in the current context

It is also not found in "Windows" dropdown.

**Comment by pgilmorepf** [comment]
We've got a few basic fixes coming out for 5.6 soon.
I'm fairly certain I'll have it published tomorrow.  Stay tuned.

**Comment by PlayFabJenkinsBot** [comment]
Should be fixed now!
