### ISSUE TITLE
Does not work in 5.5 beta

### ISSUE THREAD

**Issue by dylanh724** [PlayFab/UnityEditorExtensions#48]
Worked fine in 5.4 stable

```
Assets/PlayFabEditorExtensions/Editor/Scripts/PlayFabEditorSDK/PlayFabEditorHttp.cs(12,36): error CS0234: The type or namespace name Networking' does not exist in the namespaceUnityEngine.Experimental'. Are you missing an assembly reference?
```

#if UNITY_5_4
    using UnityEngine.Networking;
**#else
    using UnityEngine.Experimental.Networking;**
#endif

**Comment by zac-playfab** [comment]
Hey Dylanh, Do you have the latest EdEx version? At this point you might want to uninstall manually and apply the [latest (.993) build](https://github.com/PlayFab/UnityEditorExtensions/releases/tag/0.0.993).

This should be resolved as of [this](https://github.com/PlayFab/UnityEditorExtensions/pull/36) commit.

Let me know any details you have if you continue to have issues.

-Z
